#!/bin/bash
# Block ad serving and tracking system-wide even before a request is issued to them.

SOURCE='http://someonewhocares.org/hosts/zero/hosts'
TARGET='/etc/hosts'


# source: http://support.apple.com/kb/HT5343
clear_dns_cache() {
	if sw_vers -productVersion | grep -q 10.6
	then sudo dscacheutil -flushcache
	else sudo killall -HUP mDNSResponder
	fi

	echo 'DNS cache flushed.'
}

block() {
	sudo curl $SOURCE --show-error -# --output $TARGET && # -# is "show progress as a bar instead of full metrics"
	echo 'Hosts file updated.'
}

unblock() {
	sudo rm $TARGET &&
	echo 'Hosts file deleted.'
}

should_update() {
	local modification_time=$(lwp-request -m 'HEAD' "$SOURCE" | grep 'Last-Modified' | cut -d ':' -f 2- | xargs echo)	# `xargs echo` to trim leading whitespace
	local modification_time_epoch=$(LANG=en_US date -j -f "%a, %d %b %Y %T %Z" "$modification_time" "+%s")	# we need to specify the locale for this command to allow `date` to parse the date no matter the machine's locale
	local update_time=$(stat -f %m "$TARGET")

	if [[ $last_modified_epoch -gt $update_time ]]
	then
		echo "Recent update from $modification_time."
		return 0
	else
		echo "No new updates since $modification_time."
		return 1
	fi
}


if [[ $1 == 'off' ]]
then unblock && clear_dns_cache
else
	if ! [[ -a "$TARGET" ]] || should_update
	then block && clear_dns_cache
	fi
fi
